/*
 사용자 생성
 */

CREATE USER BLUNA IDENTIFIED BY "BLUNA123!@"
PROFILE DEFAULT
ACCOUNT UNLOCK;

GRANT CREATE JOB TO BLUNA;
GRANT CREATE PROCEDURE TO BLUNA;
GRANT CREATE SEQUENCE TO BLUNA;
GRANT CREATE TABLE TO BLUNA;
GRANT CREATE TRIGGER TO BLUNA;
GRANT CREATE VIEW TO BLUNA;
GRANT CREATE SESSION TO BLUNA;
GRANT RESOURCE, CONNECT TO BLUNA;